version: '3.8'

networks:
  glazing-ai-network:
    name: glazing-ai-network

services:
  postgres:
    image: postgres:15-alpine
    container_name: glazing-ai-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: glazingai
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - glazing-ai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: glazing-ai-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - glazing-ai-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    name: glazing-ai-postgres-data
  redis-data:
    name: glazing-ai-redis-data 