version: '3.8'

networks:
  glazing-ai-network:
    name: glazing-ai-network

services:
  postgres:
    image: postgres:15-alpine
    container_name: glazing-ai-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: glazingai
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - glazing-ai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: glazing-ai-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - glazing-ai-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: glazing-ai-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - glazing-ai-network
    volumes:
      - ./apps/api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=glazingai
      - POSTGRES_HOST=postgres

volumes:
  postgres-data:
    name: glazing-ai-postgres-data
  redis-data:
    name: glazing-ai-redis-data
